### ISSUE TITLE
QGIS Workshop Recommendations 

### ISSUE THREAD

**Issue by MeyaSaenzZagar** [ucdavisdatalab/Intro-to-Desktop-GIS-with-QGIS#8]
QGIS Workshop Recommendations

5.2: It may give the reader a better understanding if you include an example for raster data similar to the example given for vector data

8.2: Step 6: If the Direct Transformation dialog pane does not pop up do you still need to change the coordinate system? If not I would suggest specifying this. 

8.2.1: 
It may be helpful to give a sentence explaining what shapefiles are if it is expected that the student has no other background knowledge.
At the beginning of the tutorial, it references the Open Source Manager and then continues to call it the Source Manager so it may be helpful to add “Open” to the other sections this is referenced in. 
When selecting multiple files to add it mentioned hitting the Ctrl button but on a Mac it is the command button so including that too could help out. 

8.2.2: Step 6: After selecting WGS 84 it might be helpful to say click “Okay”

10: Step 1: could be helpful to describe the icon to Open Layer Styling Panel
     Step 4: the screenshots of the table and map are super helpful!

11.1: Step 8: Add hit “apply” once you have selected your color 

11.3: Step 4: describe that the = can be found at the bottom of the white box

13: For the step where you are selecting by attribute it may be helpful to list the steps numerically so it matches the format of the rest of the tutorial.

**Comment by MicheleTobias** [comment]
Thanks, Meya! It's helpful to see the spots where you had some confusion. I made most of the suggested changes. I'll merge those soon.
